language: node_js

node_js:
  - "8"
  - "10"
  - "11"
  - "12"

services:
  - postgresql

before_script:
  - psql -c 'create database postgres;' -U postgres

after_script:
  - npm i -g coveralls
  - npx nyc report --reporter=text-lcov | coveralls
